export const HOME_PATH = '/'
export const ARTICLE_PATH = '/Article'
export const ARTICLE_DETAIL_PATH = '/ArticleDetail/:id'
export const PHOTOGRAPH_PATH = '/Photograph'
export const ABOUTME_PATH = '/AboutMe'